// const url = "https://api-web.nhle.com/v1/skater-stats-leaders/20232024/2?categories=goals&limit=18";
// try {
//     fetch(url).then((response)=>{

//         response.json().then((json)=>{
//             modelStats.setData(json);
//         });

//     }, (error)=>{
//         console.error(error.message);
//     });
//     if (!response.ok) {
//         throw new Error(`Response status: ${response.status}`);
//     }

//     // const json = await response.json();
//     // console.log(json);
    
//     // modelStats.setData(json);

// } catch (error) {
//     console.error(error.message);
// }

modelPageStats.setData([{
    id: 8479318,
    firstName: "Auston",
    lastName: "Matthews",
    sweaterNumber: 34,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/TOR/8479318.png",
    teamAbbrev: "TOR",
    teamName: "Maple Leafs",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/TOR_light.svg",
    position: "C",
    value: 69,
},
{
    id: 8477933,
    firstName: "Sam",
    lastName: "Reinhart",
    sweaterNumber: 13,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/FLA/8477933.png",
    teamAbbrev: "FLA",
    teamName: "Panthers",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg",
    position: "C",
    value: 57,
},
{
    id: 8475786,
    firstName: "Zach",
    lastName: "Hyman",
    sweaterNumber: 18,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/EDM/8475786.png",
    teamAbbrev: "EDM",
    teamName: "Oilers",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
    position: "L",
    value: 54,
},
{
    id: 8477492,
    firstName: "Nathan",
    lastName: "MacKinnon",
    sweaterNumber: 29,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/COL/8477492.png",
    teamAbbrev: "COL",
    teamName: "Avalanche",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/COL_light.svg",
    position: "C",
    value: 51,
},
{
    id: 8478550,
    firstName: "Artemi",
        cs: "Artěmij",
        sk: "Artemij",
    lastName: "Panarin",
    sweaterNumber: 10,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/NYR/8478550.png",
    teamAbbrev: "NYR",
    teamName: "Rangers",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg",
    position: "L",
    value: 49,
},
{
    id: 8476887,
    firstName: "Filip",
    lastName: "Forsberg",
    sweaterNumber: 9,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/NSH/8476887.png",
    teamAbbrev: "NSH",
    teamName: "Predators",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/NSH_light.svg",
    position: "L",
    value: 48,
},
{
    id: 8477956,
    firstName: "David",
    lastName: "Pastrnak",
        cs: "Pastrňák",
        sk: "Pastrňák",
    sweaterNumber: 88,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/BOS/8477956.png",
    teamAbbrev: "BOS",
    teamName: "Bruins",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/BOS_20232024_light.svg",
    position: "R",
    value: 47,
},
{
    id: 8478864,
    firstName: "Kirill",
    lastName: "Kaprizov",
    sweaterNumber: 97,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/MIN/8478864.png",
    teamAbbrev: "MIN",
    teamName: "Wild",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg",
    position: "L",
    value: 46,
},
{
    id: 8478010,
    firstName: "Brayden",
    lastName: "Point",
    sweaterNumber: 21,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/TBL/8478010.png",
    teamAbbrev: "TBL",
    teamName: "Lightning",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg",
    position: "C",
    value: 46,
},
{
    id: 8476453,
    firstName: "Nikita",
    lastName: "Kucherov",
        cs: "Kučerov",
        fi: "Kutsherov",
        sk: "Kučerov",
    sweaterNumber: 86,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/TBL/8476453.png",
    teamAbbrev: "TBL",
    teamName: "Lightning",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg",
    position: "R",
    value: 44,
},
{
    id: 8478420,
    firstName: "Mikko",
    lastName: "Rantanen",
    sweaterNumber: 96,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/COL/8478420.png",
    teamAbbrev: "COL",
    teamName: "Avalanche",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/COL_light.svg",
    position: "R",
    value: 42,
},
{
    id: 8471675,
    firstName: "Sidney",
    lastName: "Crosby",
    sweaterNumber: 87,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/PIT/8471675.png",
    teamAbbrev: "PIT",
    teamName: "Penguins",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/PIT_light.svg",
    position: "C",
    value: 42,
},
{
    id: 8476539,
    firstName: "Jonathan",
    lastName: "Marchessault",
    sweaterNumber: 81,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/VGK/8476539.png",
    teamAbbrev: "VGK",
    teamName: "Golden Knights",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/VGK_light.svg",
    position: "R",
    value: 42,
},
{
    id: 8477934,
    firstName: "Leon",
    lastName: "Draisaitl",
    sweaterNumber: 29,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/EDM/8477934.png",
    teamAbbrev: "EDM",
    teamName: "Oilers",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
    position: "C",
    value: 41,
},
{
    id: 8477939,
    firstName: "William",
    lastName: "Nylander",
    sweaterNumber: 88,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/TOR/8477939.png",
    teamAbbrev: "TOR",
    teamName: "Maple Leafs",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/TOR_light.svg",
    position: "R",
    value: 40,
},
{
    id: 8474564,
    firstName: "Steven",
    lastName: "Stamkos",
    sweaterNumber: 91,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/TBL/8474564.png",
    teamAbbrev: "TBL",
    teamName: "Lightning",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg",
    position: "C",
    value: 40,
},
{
    id: 8478444,
    firstName: "Brock",
    lastName: "Boeser",
    sweaterNumber: 6,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/VAN/8478444.png",
    teamAbbrev: "VAN",
    teamName: "Canucks",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/VAN_light.svg",
    position: "R",
    value: 40,
},
{
    id: 8475184,
    firstName: "Chris",
    lastName: "Kreider",
    sweaterNumber: 20,
    headshot: "https://assets.nhle.com/mugs/nhl/20232024/NYR/8475184.png",
    teamAbbrev: "NYR",
    teamName: "Rangers",
    teamLogo: "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg",
    position: "L",
    value: 39,
}]);